algoritmo "Aula05Ex02"
// Função : Mostrar saldo inicial do usuário, definido como 500 e somar a um valor de depósito variável
// Autor : sproutjourney

var

saldoFim, saldoIni, dep : Real

inicio

saldoIni <- 500
         Escreva("Digite o valor do depósito: ")
         Leia(dep)
         Escreval("O seu saldo INICIAL era: ", saldoIni)
         Escreval("O valor do seu depósito foi de: ", dep)
         Escreval("O seu saldo ATUAL é: ", (saldoIni+dep))

fimalgoritmo
